// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbuSn719MxlpWuow9vfsfYFe_rP8QP5LY',
    appId: '1:385255613059:web:8ed724a690c41052e071b6',
    messagingSenderId: '385255613059',
    projectId: 'cli-connet',
    authDomain: 'cli-connet.firebaseapp.com',
    storageBucket: 'cli-connet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM-WK5No0EEWP6vuri6AfDv3601vdJ03s',
    appId: '1:385255613059:android:7152174caf6dbc39e071b6',
    messagingSenderId: '385255613059',
    projectId: 'cli-connet',
    storageBucket: 'cli-connet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA92NwRc-2XuNaECXJebNOG-OHf5-oqjKg',
    appId: '1:385255613059:ios:2691786b1ad868d6e071b6',
    messagingSenderId: '385255613059',
    projectId: 'cli-connet',
    storageBucket: 'cli-connet.appspot.com',
    iosBundleId: 'com.example.chatBox2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA92NwRc-2XuNaECXJebNOG-OHf5-oqjKg',
    appId: '1:385255613059:ios:2691786b1ad868d6e071b6',
    messagingSenderId: '385255613059',
    projectId: 'cli-connet',
    storageBucket: 'cli-connet.appspot.com',
    iosBundleId: 'com.example.chatBox2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbuSn719MxlpWuow9vfsfYFe_rP8QP5LY',
    appId: '1:385255613059:web:642e6fb66c12450de071b6',
    messagingSenderId: '385255613059',
    projectId: 'cli-connet',
    authDomain: 'cli-connet.firebaseapp.com',
    storageBucket: 'cli-connet.appspot.com',
  );
}
